<a href="https://colab.research.google.com/github/datsay/kg-enhanced-qa-mintaka/blob/main/experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install datasets requests tqdm

Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (4.8.5)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (3.32.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.1.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets) (2.2.3)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (1.29.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.24.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

### 1. Downloading the Mintaka JSON file

In [2]:
import json
import requests

# 1. Download raw Mintaka test split
url = "https://raw.githubusercontent.com/amazon-science/mintaka/main/data/mintaka_test.json"
print("Downloading Mintaka dataset...")
headers = {"User-Agent": "Mozilla/5.0"}
response = requests.get(url, headers=headers)
raw_data = response.json()

# 2. Filter for multihop and intersection questions
filtered_data = [
    item for item in raw_data
    if item.get("complexityType") in ["multihop", "intersection"]
][:100]

print(f"Successfully loaded {len(filtered_data)} evaluation samples.")

# 3. Clean and parse entities and gold answers
processed_samples = []
for item in filtered_data:
    # Extract Wikidata entity IDs and labels from questionEntity
    entities = [
        {"id": e.get("name"), "label": e.get("label")}
        for e in item.get("questionEntity", [])
        if e.get("name")
    ]

    # Extract gold answer strings safely
    gold_answers = []
    ans_obj = item.get("answer") or {}

    if ans_obj.get("mention"):
        gold_answers.append(ans_obj["mention"])

    answer_list = ans_obj.get("answer") or []
    for a in answer_list:
        if isinstance(a, dict) and "label" in a:
            label = a["label"]
            if isinstance(label, dict):
                gold_answers.append(label.get("en"))
            elif isinstance(label, str):
                gold_answers.append(label)
        elif isinstance(a, str):
            gold_answers.append(a)

    # Deduplicate answer strings
    gold_answers = list(set([g for g in gold_answers if g]))

    processed_samples.append({
        "id": item["id"],
        "question": item["question"],
        "complexity": item["complexityType"],
        "entities": entities,
        "gold_answers": gold_answers
    })

# 4. Preview the first parsed sample
first = processed_samples[0]
print("\n--- Example Data Sample ---")
print("ID:", first["id"])
print("Question:", first["question"])
print("Complexity:", first["complexity"])
print("Entities:", first["entities"])
print("Gold Answers:", first["gold_answers"])

Downloading Mintaka dataset...
Successfully loaded 100 evaluation samples.

--- Example Data Sample ---
ID: fae46b21
Question: What man was a famous American author and also a steamboat pilot on the Mississippi River?
Complexity: intersection
Entities: [{'id': 'Q1497', 'label': 'Mississippi River'}, {'id': 'Q846570', 'label': 'Americans'}]
Gold Answers: ['Mark Twain']

### 2. Knowledge Graph Retrieval (Wikidata SPARQL)

In [3]:
import time

def fetch_wikidata_triples(entity_id, limit=5):
    """
    Fetches up to `limit` direct relational triples for a given Wikidata entity ID.
    Returns triples in human-readable string format: (Subject Label | Predicate Label | Object Label).
    """
    url = "https://query.wikidata.org/sparql"

    # SPARQL query retrieving human-readable labels in English
    sparql_query = f"""
    SELECT ?propLabel ?valLabel WHERE {{
      wd:{entity_id} ?p ?statement .
      ?statement ?ps ?val .
      ?prop wikibase:claim ?p .
      ?prop wikibase:statementProperty ?ps .

      # Filter for items that have an English label
      SERVICE wikibase:label {{ bd:serviceParam wikibase:language "en". }}
      FILTER(isIRI(?val))
    }}
    LIMIT {limit}
    """

    headers = {
        # Custom User-Agent to comply with Wikidata query API policies
        "User-Agent": "AcademicPosterResearchBot/1.0 (nlp-module-poster-project)"
    }

    try:
        response = requests.get(url, params={"query": sparql_query, "format": "json"}, headers=headers, timeout=10)
        if response.status_code == 200:
            results = response.json().get("results", {}).get("bindings", [])
            triples = []
            for r in results:
                prop = r.get("propLabel", {}).get("value")
                val = r.get("valLabel", {}).get("value")
                if prop and val:
                    triples.append(f"{prop} -> {val}")
            return triples
        else:
            return []
    except Exception as e:
        return []

# Test the function on the entities from the first sample
print("Testing Wikidata triple retrieval on the first sample...")
test_sample = processed_samples[0]
print("Question:", test_sample["question"])

for ent in test_sample["entities"]:
    print(f"\nEntity: {ent['label']} ({ent['id']})")
    triples = fetch_wikidata_triples(ent['id'], limit=5)
    for t in triples:
        print(f"  - ({ent['label']}) --[{t}]")
    time.sleep(1) # Polite pause for the API

Testing Wikidata triple retrieval on the first sample...
Question: What man was a famous American author and also a steamboat pilot on the Mississippi River?

Entity: Mississippi River (Q1497)
  - (Mississippi River) --[tributary -> Salt River]
  - (Mississippi River) --[described by source -> Brockhaus and Efron Encyclopedic Dictionary]
  - (Mississippi River) --[tributary -> Des Moines River]
  - (Mississippi River) --[tributary -> Sucker Creek]
  - (Mississippi River) --[tributary -> Cinque Hommes Creek]

Entity: Americans (Q846570)
  - (Americans) --[has part(s) -> Afghan Americans]
  - (Americans) --[has part(s) -> Saudi Americans]
  - (Americans) --[has part(s) -> Tongan Americans]
  - (Americans) --[has part(s) -> Eastern European Americans]
  - (Americans) --[has part(s) -> Bolivian Americans]

### Install huggingface_hub

In [5]:
!pip install -q huggingface_hub

### 3. LLM Inference Function

In [5]:
!pip install -q transformers accelerate torch

import torch
from transformers import pipeline

print("Loading Qwen2.5-3B onto T4 GPU...")
pipe = pipeline(
    "text-generation",
    model="Qwen/Qwen2.5-3B-Instruct",
    torch_dtype=torch.float16,
    device_map="auto"
)
print("Model loaded successfully!")

def query_llm(prompt, temperature=0.01, max_new_tokens=64):
    messages = [
        {"role": "system", "content": "You are a concise fact-based assistant. Answer the question in as few words as possible. Do not explain."},
        {"role": "user", "content": prompt}
    ]
    try:
        output = pipe(
            messages,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=pipe.tokenizer.eos_token_id
        )
        return output[0]["generated_text"][-1]["content"].strip()
    except Exception as e:
        return f"Error: {e}"

# Test query
test_q = processed_samples[0]["question"]
print("Question:", test_q)
print("Answer:  ", query_llm(test_q))

Loading Qwen2.5-3B onto T4 GPU...

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'pad_token_id', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.

Model loaded successfully!
Question: What man was a famous American author and also a steamboat pilot on the Mississippi River?

[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Answer:   Mark Twain

### 4. Comparative Evaluation Loop (Baseline vs. KG-Enhanced)

In [6]:
from tqdm import tqdm

def format_kg_context(entities):
    """
    Fetches triples for all identified entities and formats them as a clean text context block.
    """
    all_triples = []
    for ent in entities:
        ent_id = ent.get("id")
        ent_label = ent.get("label", "Entity")
        if ent_id:
            triples = fetch_wikidata_triples(ent_id, limit=4)
            for t in triples:
                all_triples.append(f"{ent_label} -> {t}")
            time.sleep(0.2)  # Polite delay for Wikidata SPARQL endpoint

    if not all_triples:
        return "No external knowledge retrieved."
    return "\n".join(all_triples)

def run_evaluation(samples, limit=20):
    """
    Runs the comparative experiment over `limit` samples and stores the structured results.
    """
    results = []
    eval_set = samples[:limit]

    print(f"Starting local GPU evaluation on {len(eval_set)} samples...\n")

    for item in tqdm(eval_set, desc="Evaluating"):
        question = item["question"]
        gold = item["gold_answers"]
        entities = item["entities"]

        # 1. Baseline Zero-Shot Prompt
        baseline_prompt = f"Question: {question}\nAnswer:"
        baseline_answer = query_llm(baseline_prompt)

        # 2. KG-Augmented Prompt
        kg_context = format_kg_context(entities)
        kg_prompt = (
            f"Context Information:\n{kg_context}\n\n"
            f"Question: {question}\n"
            f"Answer the question concisely using the provided context if relevant.\nAnswer:"
        )
        kg_answer = query_llm(kg_prompt)

        results.append({
            "id": item["id"],
            "question": question,
            "gold_answers": gold,
            "complexity": item["complexity"],
            "retrieved_context": kg_context,
            "baseline_pred": baseline_answer,
            "kg_pred": kg_answer
        })

    with open("eval_results.json", "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    print(f"\nExperiment complete. Saved {len(results)} outputs to 'eval_results.json'.")
    return results

# Run the 20-sample batch to verify clean outputs
experiment_results = run_evaluation(processed_samples, limit=20)

Starting local GPU evaluation on 20 samples...

Evaluating:   0%|          | 0/20 [00:00<?, ?it/s][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:   5%|▌         | 1/20 [00:03<01:05,  3.44s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  10%|█         | 2/20 [00:05<00:42,  2.39s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  15%|█▌        | 3/20 [00:08<00:46,  2.76s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  20%|██        | 4/20 [00:12<00:53,  3.33s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  25%|██▌       | 5/20 [00:14<00:40,  2.70s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  30%|███       | 6/20 [00:16<00:36,  2.60s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  35%|███▌      | 7/20 [00:18<00:30,  2.37s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  40%|████      | 8/20 [00:19<00:25,  2.12s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  45%|████▌     | 9/20 [00:21<00:20,  1.89s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  50%|█████     | 10/20 [00:23<00:19,  2.00s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  55%|█████▌    | 11/20 [00:26<00:19,  2.22s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  60%|██████    | 12/20 [00:28<00:16,  2.12s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  65%|██████▌   | 13/20 [00:29<00:13,  1.94s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  70%|███████   | 14/20 [00:30<00:10,  1.73s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  75%|███████▌  | 15/20 [00:33<00:09,  1.89s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  80%|████████  | 16/20 [00:35<00:08,  2.13s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  85%|████████▌ | 17/20 [00:38<00:06,  2.19s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  90%|█████████ | 18/20 [00:39<00:03,  1.88s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating:  95%|█████████▌| 19/20 [00:40<00:01,  1.66s/it][transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Evaluating: 100%|██████████| 20/20 [00:42<00:00,  2.12s/it]

Experiment complete. Saved 20 outputs to 'eval_results.json'.

In [7]:
import pandas as pd

# Load into a clean DataFrame for side-by-side inspection
df = pd.DataFrame(experiment_results)

# Display key comparison columns
display_cols = ["id", "question", "gold_answers", "baseline_pred", "kg_pred"]
df[display_cols].head(10)

,id,question,gold_answers,baseline_pred,kg_pred
0,fae46b21,What man was a famous American author and also...,[Mark Twain],Mark Twain,Mark Twain
1,bfc9807b,What state is the author of Misery from?,[Maine],Pennsylvania,Unknown
2,16caac54,Which Harry Potter movie is directed by Alfons...,[Harry Potter and the Prisoner of Azkaban],Harry Potter and the Cursed Child,Harry Potter and the Prisoner of Azkaban
3,37b5b4fc,Which movie scored 100% on Rotten Tomatoes and...,[Grave of the Fireflies],Your Name,"No movie scored 100% on Rotten Tomatoes, but T..."
4,28332e38,Which live-action movie did Adam Sandler produ...,[Jack and Jill],Just Go With It,None
5,57ed9851,Which actor starred in Jerry Maguire and was b...,[Tom Cruise],Gregg Henry,Q135206902
6,293f70d0,Which movie was directed by David Fincher and ...,[Fight Club],Zodiac,The Social Network
7,2568c6c0,Which action movie was released in 1988 and fe...,[Die Hard],Die Hard,Die Hard
8,39f078ad,Which actor played both Han Solo and Indiana J...,[Harrison Ford],Harrison Ford,N/A
9,120036fc,Which movie is Bruce Lee most well known for t...,"[Enter The Dragon, Enter the Dragon]",Fist of Fury,Enter the Dragon

In [8]:
df[display_cols].tail(10)

,id,question,gold_answers,baseline_pred,kg_pred
10,c5157a43,"What musical was the first ""talkie"" and was re...",[The Jazz Singer],The Jazz Singer,42nd Street
11,d4a4ad9f,Who played park owner John Hammond in Jurassic...,[Richard Attenborough],None,None of the given information answers the ques...
12,c0db4c57,Which movie was produced by Steven Spielberg a...,[Memoirs of a Geisha],War of the Worlds,No answer provided within given context.
13,d7a1ef27,Which movie starred Edward Norton and Brad Pitt?,[Fight Club],Fight Club,No movie information found.
14,24e8eae1,Which movie was directed by George Lucas and c...,[THX 1138],American Graffiti,None of the information provided is about a mo...
15,e5d1c788,"Which actor is from Orange, NJ and starred in ...",[Roy Scheider],Richard Dreyfuss,"No actor is mentioned from Orange, NJ. The que..."
16,28c79e06,Which 1990 Tim Burton movie starred Johnny Depp?,[Edward Scissorhands],Sweeney Todd: The Demon Barber of Fleet Street,Sweeney Todd: The Demon Barber of Fleet Street
17,d28e564f,Which movie actress is married to Cooke Marone...,[Jennifer Lawrence],Tessa Thompson,None of the given information answers the ques...
18,b6fbf31f,Which movie was directed by Peter Jackson and ...,[The Lord of the Rings: The Fellowship of the ...,King Kong,Not enough information
19,fc92d185,Which movie starred Daniel Craig and came out ...,[Casino Royale],Casino Royale,No answer provided with given context.